behaviors:
  PushBlock:
    trainer_type: sac_transfer
    hyperparameters:
      learning_rate: 0.0003
      learning_rate_schedule: constant
      model_lr_schedule: linear
      batch_size: 128
      buffer_size: 2000000
      buffer_init_steps: 0
      tau: 0.005
      steps_per_update: 10.0
      save_replay_buffer: false
      init_entcoef: 0.05
      reward_signal_steps_per_update: 10.0
      transfer_target: true
      transfer_from: "results/pushblock_sac_f256_enc-actor/PushBlock"
      forward_layers: 2
      feature_size: 256
      encode_actor: true
      encode_critic: false
      norm_latent: true
      norm_reward: true
      predict_delta: false
      model_raw: false
      coeff: 10.0
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 2000000
    time_horizon: 64
    summary_freq: 100000
    threaded: true