behaviors:
  3DBallHard:
    trainer_type: ppo_transfer
    hyperparameters:
      batch_size: 120
      buffer_size: 12000
      learning_rate: 0.0003
      beta: 0.001
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
      model_lr_schedule: linear
      transfer_target: true
      transfer_from: "results/ball_ppo_f8_auxiliary/3DBall"
      detach_next: true
      forward_layers: 2
      feature_size: 8
      encode_actor: true
      encode_critic: false
      norm_latent: true
      norm_reward: false
      predict_delta: false
      coeff: 10
    network_settings:
      normalize: false
      hidden_units: 64
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 500000
    time_horizon: 1000
    summary_freq: 12000
    threaded: true
