behaviors:
  3DBallHard:
    trainer_type: sac_transfer
    hyperparameters:
      learning_rate: 0.0003
      learning_rate_schedule: constant
      model_lr_schedule: linear
      batch_size: 64
      buffer_size: 300000
      buffer_init_steps: 0
      tau: 0.005
      steps_per_update: 10.0
      save_replay_buffer: false
      init_entcoef: 1.0
      reward_signal_steps_per_update: 10.0
      transfer_target: true
      transfer_from: "results/ball_sac_f8_enc-ac-cri_nolinear_0/3DBall"
      forward_layers: 2
      feature_size: 8
      detach_next: false
      encode_actor: true
      encode_critic: true
      norm_latent: true
      norm_reward: true
      predict_delta: false
      model_raw: false
      coeff: 10
    network_settings:
      normalize: false
      hidden_units: 64
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 300000
    time_horizon: 1000
    summary_freq: 12000
    threaded: true
